### ISSUE TITLE
stack build error when using accelerate-llvm

### ISSUE THREAD

**Issue by chmlxj** [AccelerateHS/accelerate-llvm#14]
I am trying to build my own project that uses "accelerate-llvm" package, here were the steps I did:

1) stack new "project"
2) copy accelerate-llvm under project foler
3) successfully built accelerate-llvm (using stack install)
4) edited stack.yaml of "project" to refer to accelerate-llvm folder
5) stack build

**I see error message as following:**

> In the dependencies for accelerate-llvm-1.0.0.0:
>     accelerate-0.15.1.0 must match ==1.0.*
> needed due to accelerate-llvm-ptx-1.0.0.0 -> accelerate-llvm-1.0.0.0

**my stack.yaml file looks like this:**

> packages:
>   - '.'
>   - accelerate-llvm/accelerate-llvm-ptx/
>   - accelerate-llvm/accelerate-llvm/
>   - accelerate-llvm/accelerate-llvm-native/
> 
> extra-deps:
>   - cuda-0.7.5.2
>   - llvm-general-3.5.1.2
>   - llvm-general-pure-3.5.1.0
>   - chaselev-deque-0.5.0.5
>   - libffi-0.1
> 
> flags: {}
> 
> extra-package-dbs:
>   - '.'
>   - accelerate-llvm/.stack-work/install/x86_64-linux-nopie/lts-8.0/8.0.2/pkgdb
>

**Comment by tmcdonell** [comment]
You need to get `accelerate` from github as well; the version on Hackage is too old.

You can use something like the following to just pull both `accelerate` and `accelerate-llvm` straight from github. You only need to pull them into a local directory yourself if you want to edit the packages, but feel free to replace these `location...` entries with just a local directory path.

```yaml
# ghc-8.0.2
resolver: lts-8.0

packages:
- '.'

- location:
    git:    https://github.com/AccelerateHS/accelerate.git
    commit: b6c1621ce2993b76b858ee2af4aa46b81fe95202
  extra-dep: true

- location:
    git:    https://github.com/AccelerateHS/accelerate-llvm.git
    commit: 48744386436d664c59145c8d80a8851c53716ea9
  extra-dep: true
  subdirs:
    - 'accelerate-llvm'
    - 'accelerate-llvm-native'
    - 'accelerate-llvm-ptx'

- location:
    git:    https://github.com/tmcdonell/llvm-general.git
    # commit: 8971e275fe56dfd0090ac777e38e6dd641a0306a # 3.5
    # commit: 3f0b8003664e0a5f9ed94434919167fbf95025ec # 3.8
    commit: 960a6028bce3d98c2050fd9d45bbdaf797bec3f4 # 3.9
  extra-dep: true
  subdirs:
    - 'llvm-general'
    - 'llvm-general-pure'

extra-deps:
- 'chaselev-deque-0.5.0.5'
- 'cuda-0.7.5.2'
- 'libffi-0.1'
- 'nvvm-0.7.5.1'
- 'unique-0'

# Override default flag values for local packages and extra-deps
flags:
  llvm-general:
    shared-llvm: true
  accelerate:
    debug: false
    ekg:   false
  accelerate-llvm-native:
    debug: false
  accelerate-llvm-ptx:
    debug: false
    nvvm:  false
```

In the `llvm-general` section, uncomment the relevant SHA for the version of LLVM you have installed.

Note that in the flags section the `llvm-general:shared-llvm` flag is important. The other entries are there for convenience in case you want to turn debugging features on; look at generated code, get timing information, etc...

The [`accelerate-examples`](https://github.com/AccelerateHS/accelerate-examples) package contains example `stack.yaml` files as well.
