### ISSUE TITLE
conditional code causes segfault when there's five or more layers of embedded conditionals.

### ISSUE THREAD

**Issue by skynet1** [AccelerateHS/accelerate-llvm#33]
I am submitting a...
- [x] bug report
- [ ] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description
When I run the following code in GHCI:
`import Data.Array.Accelerate as A

import Data.Array.Accelerate.LLVM.Native as N

let xs = use (fromList (Z:.10) (Prelude.take 10 [0..]) :: Vector Double)

let ys = use (fromList (Z:.10) [0, 1, 2, 3, 4, 0, 1, 2, 3, 4] :: Vector Int)

let f :: Exp Double -> Exp Int -> Exp Double ; f x y = (y A.== 0) A.? (1,(y A.== 1) A.? (A.max 0 x,(y A.== 2) A.? (sin x, (y A.== 3) A.? (exp x, (y A.== 4) A.? (sqrt x, 1.0 / x)))))

N.run $ A.zipWith (\x -> \y -> f x y) xs ys
`
The program crashes with a segmentation fault.

## Steps to reproduce (for bugs)

 1.
 2.
 3.

## Your environment

- Version used: accelerate 1.1.1.0 
- Backend(s) used and version: accelerate-llvm-native 1.1.0.1
- GHC version: 8.2.2
- Operating system and version: Debian 8.10
- Link to your project:
- If this is a bug with the GPU backend, include the output of `nvidia-device-query`:

**Comment by tmcdonell** [comment]
hm, I couldn't reproduce this on my machine (macOS, ivybridge). Follow-up questions:

  1. LLVM version?
  1. What CPU are you using? (it may be using instructions which my CPU doesn't have)
  1. Does it still segfault when running with HEAD?

**Comment by tmcdonell** [comment]
I managed to reproduce this on a ubuntu box with 1.1.1.0, but the latest git seems to work. Could you see if it works for you as well?

Try something like the following `stack.yaml`:

```yaml
resolver: lts-10.7

packages:
- '.'

extra-deps:
- git:    https://github.com/tmcdonell/accelerate.git
  commit: f30c36ebd4a3f1d8c333a24f133b6bc962d3f0b8

- git:    https://github.com/tmcdonell/accelerate-llvm.git
  commit: c1e241634c2b9e18c5023ea04e7aeb147a683abc
  subdirs:
    - 'accelerate-llvm'
    - 'accelerate-llvm-native'
    - 'accelerate-llvm-ptx'
```
