### ISSUE TITLE
[BUG] libnvvm.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by largeword** [AccelerateHS/accelerate-llvm#94]
Hi, libnvvm.so was missing during compiling accelerate-llvm-ptx.

**Description**
When building an empty project with this package, there was an error showed up:
```
accelerate-llvm-ptx> [24 of 47] Compiling Language.Haskell.TH.Extra
accelerate-llvm-ptx> [25 of 47] Compiling Data.Array.Accelerate.LLVM.PTX.Compile.Libdevice.TH
accelerate-llvm-ptx> [26 of 47] Compiling Data.Array.Accelerate.LLVM.PTX.Compile.Libdevice.Load
accelerate-llvm-ptx> <command line>: libnvvm.so.4: cannot open shared object file: No such file or directory
Progress 1/2

--  While building package accelerate-llvm-ptx-1.3.0.0 (scroll up to its section to see the error) using:
      /home/xxx/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_3.4.1.0_ghc-9.0.2 --verbose=1 --builddir=.stack-work/dist/x86_64-linux/Cabal-3.4.1.0 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

But I properly installed CUDA and GPU driver:
```
$ sudo find / -name nvvm
/usr/local/cuda-11.8/nvvm
find: ‘/run/user/1000/doc’: Permission denied
find: ‘/run/user/1000/gvfs’: Permission denied
/home/xxx/.cabal/packages/hackage.haskell.org/nvvm

$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

**Steps to reproduce**
In stack.yaml:
```
resolver:
  compiler: ghc-9.0.2

packages:
- .

extra-deps:
- github: AccelerateHS/accelerate
  commit: 5971c5d8e4dbba28d2017e7ce422cf46a20197cb

- github: AccelerateHS/accelerate-llvm
  commit: 2cd65569c875477b5250d54f0d0738d8ee28e597
  subdirs:
    - accelerate-llvm
    - accelerate-llvm-native
    - accelerate-llvm-ptx

- github: llvm-hs/llvm-hs
  commit: 423220bffac4990d019fc088c46c5f25310d5a33
  subdirs:
    - llvm-hs-pure
    - llvm-hs

- cuda-0.11.0.0
- nvvm-0.10.0.0

- abstract-deque-0.3
- ansi-terminal-0.11.5
- attoparsec-0.14.4
- async-2.2.4
- atomic-primops-0.8.4
- barbies-2.0.4.0
- base-orphans-0.9.0
- c2hs-0.28.8
- cabal-doctest-1.0.9
- cereal-0.5.8.3
- constraints-0.13.4
- clock-0.8.3
- colour-2.3.6
- concurrent-output-1.10.17
- data-default-class-0.1.2.0
- dlist-1.0
- double-conversion-2.0.4.2
- data-array-byte-0.1.0.1
- erf-2.0.0.0
- fail-4.9.0.0
- file-embed-0.0.15.0
- formatting-7.2.0
- half-0.3.1
- hashable-1.4.2.0
- hashtables-1.3.1
- hedgehog-1.2
- libffi-0.1
- lockfree-queue-0.2.4
- language-c-0.9.2
- lifted-async-0.10.2.4
- mmorph-1.2.0
- monad-control-1.0.3.1
- microlens-0.4.13.1
- prettyprinter-1.7.1
- prettyprinter-ansi-terminal-1.1.3
- primitive-0.8.0.0
- tasty-1.4.3
- terminal-size-0.3.4
- th-lift-instances-0.1.20
- unique-0.0.1
- unordered-containers-0.2.19.1
- utf8-string-1.0.2
- uuid-types-1.0.5
- vector-0.13.0.0
- old-locale-1.0.0.7
- optparse-applicative-0.17.0.0
- pretty-show-1.10
- random-1.2.1.1
- resourcet-1.2.6
- scientific-0.3.7.0
- tagged-0.8.7
- th-lift-0.8.3
- transformers-base-0.4.6
- transformers-compat-0.7.2
- type-equality-1
- vector-stream-0.1.0.0
- wl-pprint-annotated-0.1.0.1

- alex-3.2.7.1
- ansi-terminal-types-0.11.5
- ansi-wl-pprint-0.6.9
- distributive-0.6.2.1
- happy-1.20.1.1
- haskell-lexer-1.1.1
- integer-logarithms-1.0.3.1
- lifted-base-0.2.3.12
- splitmix-0.1.0.4
- th-abstraction-0.5.0.0
- unliftio-core-0.2.1.0

allow-newer: true
```

Then execute `$  stack build`

**Expected behaviour**
This package should be compiled without error.

**Your environment**
Include any relevant details about the environment you experienced the bug in. When reporting the versions of Accelerate packages used, include either the release number or the commit SHA if building from source.

If the bug is with the `accelerate-llvm-ptx` GPU backend, include the output of `nvidia-device-query`

 - Accelerate: 1.3.0.0
 - Accelerate backend(s): accelerate-llvm-ptx
 - GHC: 9.0.2
 - OS: Ubuntu 22.04
 - nvidia driver: 515.105.01
 - nvidia-device-query:
 ```
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "NVIDIA GeForce RTX 3080 Ti"
  CUDA Driver Version / Runtime Version          11.7 / 11.8
  CUDA Capability Major/Minor version number:    8.6
  Total amount of global memory:                 12046 MBytes (12630884352 bytes)
  (080) Multiprocessors, (128) CUDA Cores/MP:    10240 CUDA Cores
  GPU Max Clock rate:                            1710 MHz (1.71 GHz)
  Memory Clock rate:                             9501 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 6291456 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total shared memory per multiprocessor:        102400 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1536
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Managed Memory:                Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 8 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 11.7, CUDA Runtime Version = 11.8, NumDevs = 1
Result = PASS
```
